#!/bin/sh

# Errors if unresolved merge conflicts detected.
# A file must contain line starting with >>>>>>> or <<<<<<< to trigger failure.
#
# Modified from: http://jondowdle.com/2015/02/17/block-merge-conflicts-in-commits.html

__DIR__="$(cd "$(dirname "${0}")"; echo $(pwd))"

changed=$(git diff --cached --name-only --diff-filter=ACM)
[ -z "$changed" ] && exit 0

conflicts=$(cd $__DIR__/../../.. && echo $changed | xargs egrep '^[><]{7}' -H -I --line-number)
# grep returns 0 if no matches, 1 otherwise
[ $? != 0 ] && exit 0

# There are merge conflict markers. Print out the file:linenumber for each and fail.

echo >&2 "You have merge markers. Remove them (and resolve conflicts) before committing:"
for conflict in "$conflicts"; do
  echo >&2 " $(echo $conflict | cut -d':' -f1,2)"
done
exit 1
