#!/bin/sh
#
# Ensures that all dependencies are vendored properly.
# Detects any import paths that do not include the base
# import path of the project.
#
# Example: github.comcast.com/vbo/go-log/log instead of the vendored version.


ROOT_DIR="$(cd "$(dirname "${0}")"; cd "../../.."; echo $(pwd))"
cd $ROOT_DIR
# Capture the "base" import path, which all other non standard library imports must start with
base="$(go list -e)"

# List all dependencies which aren't standard library.
# Include test dependencies as well.
# Exclude all which begin with the required base.
DEPS="$(go list -e -f '{{join .Deps "\n"}}{{print "\n"}}{{join .TestImports "\n"}}{{print "\n"}}{{join .XTestImports "\n"}}' ./... \
  | sort -u \
  | xargs go list -e -f '{{if not .Standard}}{{.ImportPath}}{{end}}' \
  | egrep -v "^$base")"

[ $? != 0 ] && exit 0

# There are imports from outside this project. Print them and fail.

echo >&2 "There are imports outside \"$base\". Please fix the following:"
for dep in $DEPS; do
  # Recursively search for file containing bad import path.
  errors="$(grep -r -H --line-number -e \""$dep"\" --include "*.go" .)"
  if [ ! -z "$errors" ]
  then
    echo >&2 "$errors"
  fi
done

exit 1
