#!/usr/bin/env bash

# Searches through all dependencies. Exits with 1 if
# "testing" is imported.

# Error if PKG is imported
PKG="testing"

ROOT_DIR="$(cd "$(dirname "${0}")"; cd "../../.."; echo $(pwd))"
cd $ROOT_DIR

deps=$(go list -f '{{ join .Deps "\n"}}' ./...)

quicktest=$(echo "$deps" | grep $PKG)
[ -z "$quicktest" ] && exit 0

# $PKG is included in the dependencies. Iterate over the
# dependencies which are not in the std lib, and search for $PKG
# to be able to print which package imports $PKG.

# Find all non std lib dependencies.
localdeps=$(echo "$deps" | xargs go list -e -f '{{if not .Standard}}{{.ImportPath}}{{end}}')

echo >&2 "\"$PKG\" is being imported, please remove it from following packages:"
for dep in $localdeps; do
  testDep=$(go list -f '{{join .Deps "\n"}}' $dep | grep $PKG)
  if [ $? -ne 1 ]; then
    echo >&2 "  $dep"
    exit 1
  fi
done
